# Site settings
title: Kaffeinated Kodemonkey
phone: (720) 608-1444
email: admin@kaffeinatedkodemonkey.com
description: > # "baseurl:"
      Building Rural & Governmental Websites one presence at a time.<br />
      Understand what it means to you & how you can be part of a growing community.<br />
      This months featured bolg: Local Listings - What they and why they are important.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

twitter_username: kfn8dkodemonkey
github_username:  kfn8dkodemonkey
facebook_username: kaffeinatedkodemonkey
bookme:            https://kaffeinatedkodemonkey.youcanbook.me/

# Build settings
markdown: kramdown

permalink: /:categories/:year/:month/:day/:title.html

#test post befor publishing (set to true)
future: true
